=== mrq-cz/vocloud/worker/universal-worker/src/main/resources/configSchema.xsd
<?xml version="1.0" encoding="windows-1250"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://vocloud.rk.cz/schema"
            xmlns:tns="http://vocloud.rk.cz/schema"
            elementFormDefault="qualified">
    
    <xsd:complexType name="worker">
        <xsd:sequence>
            <xsd:element name="identifier" type="xsd:token"/>
            <xsd:element name="description" type="xsd:string"/>
            <xsd:element name="restricted" type="xsd:boolean" default="false"/>
            <xsd:element name="binaries-location" type="xsd:string"/>
            <xsd:element name="exec-command" type="tns:command-list"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="command-list">
        <xsd:sequence>
            <xsd:element name="command" type="xsd:string" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="uws-settings">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="vocloud-server-address" type="xsd:anyURI"/>
                <xsd:element name="local-address" type="xsd:anyURI"/>
                <xsd:element name="max-jobs" type="xsd:positiveInteger" default="4"/>
                <xsd:element name="description" type="xsd:string"/>
                <xsd:element name="default-destruction-interval" type="xsd:positiveInteger" minOccurs="0"/>
                <xsd:element name="max-destruction-interval" minOccurs="0" type="xsd:positiveInteger"/>
                <xsd:element name="default-execution-duration" default="3600" minOccurs="0" type="xsd:positiveInteger"/>
                <xsd:element name="max-execution-duration" default="3600" minOccurs="0" type="xsd:positiveInteger"/>
                <xsd:element name="workers">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="worker" maxOccurs="unbounded" minOccurs="0" type="tns:worker"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== mrq-cz/vocloud/worker/universal-worker/src/main/resources/uws-config.xml
<?xml version="1.0" encoding="windows-1250"?>
<ns:uws-settings
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:ns='http://vocloud.rk.cz/schema'
    xsi:schemaLocation='http://vocloud.rk.cz/schema configSchema.xsd'>
    <ns:vocloud-server-address>http://localhost:80/vocloud</ns:vocloud-server-address>
    <ns:local-address>http://localhost:80</ns:local-address>
    <ns:max-jobs>4</ns:max-jobs>
    <ns:description>Universal UWS worker</ns:description>
    <ns:default-execution-duration>3600</ns:default-execution-duration>
    <ns:max-execution-duration>3600</ns:max-execution-duration>
        <ns:workers>
            <ns:worker>
                <ns:identifier>test</ns:identifier>
                <ns:description>Testing</ns:description>
                <ns:restricted>true</ns:restricted>
                <ns:binaries-location></ns:binaries-location>
                <ns:exec-command>
                    <ns:command>python</ns:command>
                    <ns:command>-h</ns:command>
                    <ns:command>></ns:command>
                    <ns:command>manpage.txt</ns:command>
                </ns:exec-command>
            </ns:worker>
            <ns:worker>
                <ns:identifier>mirror</ns:identifier>
                <ns:description>Mirror test</ns:description>
                <ns:restricted>false</ns:restricted>
                <ns:binaries-location>c:\\Users\radio.koza\Desktop\Sources\Python\VertikalniText</ns:binaries-location>
                <ns:exec-command>
                    <ns:command>python</ns:command>
                    <ns:command>${binaries-location}\main.py</ns:command>
                    <ns:command>${config-file}</ns:command>
                    <ns:command>output.txt</ns:command>
                </ns:exec-command>
            </ns:worker>
        </ns:workers>
</ns:uws-settings>
